main:
  - name: Accueil
    url: '#about'
    weight: 10
  - name: Compétences
    url: '#skills'
    weight: 15
  - name: Expérience
    url: '#experience'
    weight: 20
  - name: Certifications
    url: '#accomplishments'
    weight: 25
  - name: Blog
    url: '#posts'
    weight: 30
  - name: Projets
    url: '#projects'
    weight: 40
  - name: Publications
    url: '#publications'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
  - name: CV
    url: uploads/resume.pdf
    weight: 70