main:
  - name: Accueil
    url: /fr/
    weight: 10
  - name: À propos
    url: /fr/about/
    weight: 15
  - name: Articles
    url: /fr/post/
    weight: 20
  - name: Projets
    url: /fr/project/
    weight: 25
  - name: Contact
    url: /fr/#contact
    weight: 30
  - name: CV
    url: uploads/resume.pdf
    weight: 40